## LEAVING THIS FILE IN CASE WE SWITCH TO USE PROPERTIES FILE FOR HIBERNATE CONFIG
## IMPORTANT: DO NOT COMMIT THIS FILE TO GIT!!!!!!!

#hibernate.connection.driver_class=org.h2.Driver
##hibernate.connection.url=jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1
##hibernate.connection.url=jdbc:postgresql://localhost:5432/recordcatalogerdev
#hibernate.connection.url=jdbc:postgresql://localhost:5432/recordcatalogerdev
#hibernate.connection.username=record_cataloger_api
#hibernate.connection.password=proximal-enfilade9RENEW
#hibernate.connection.autocommit=true
##jdbc.password=proximal-enfilade9RENEW
#
#hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
#hibernate.show_sql=true
##hibernate.hbm2ddl.auto=create-drop
#
## Database Properties
##spring.datasource.url=jdbc:postgresql://localhost:5432/recordcatalogerdev
##spring.datasource.username=record_cataloger_api
##spring.datasource.password=proximal-enfilade9RENEW
#
## Hibernate Properties
## The SQL dialect makes Hibernate generate better SQL for the chosen database
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL92Dialect
##spring.h2.console.enabled=true
## Hibernate ddl auto (create, create-drop, validate, update). DDL is the sql update. Below line says update the table if it doesn't match the @Entity
##spring.jpa.hibernate.ddl-auto=update